from interfaces.product import Product, ProductUrl


class SourceProductInputUrl(ProductUrl): ...


class SourceProduct(Product): ...


class AlternativeProductOutputUrl(ProductUrl): ...


class AlternativeProduct(Product): ...
